Random suggestion
TheNerm/Trackflix pull request #6
Opened 2023-07-17 20:46 UTC by PhOberd

2023-07-18 14:53 UTC, TheNerm requested changes
Die neue Seite schaut cool aus und ist gut eingebunden in die App. Code Kommentare waren auch eine gute Idee. Nur sollten backlog medien auch suggested werden.

2023-07-18 14:53 UTC, TheNerm commented on app/src/main/java/com/example/trackflix/fragments/random/RandomFragment.kt
> +                ((trackable.type == type)&&(trackable.progressState == "inProgress"))
Ich würde hier neben "inProgress" auch "backlog" inkludieren, weil es ja auch darum geht dass man Hilfe beim Aussuchen von einem neuen Medium braucht.

2023-07-18 14:53 UTC, TheNerm commented on app/src/main/java/com/example/trackflix/fragments/random/RandomFragment.kt
> +                trackable.progressState == "inProgress"
Hier dann das gleiche wie oben

2023-07-18 14:53 UTC, TheNerm commented on app/src/main/res/values/strings.xml
> +    <string name="randFragError">"The provided List contains no Elements that haven\'t been watched yet.\n Please check if u have trackables that have the status in Progress!"</string>
Hier sollte die Info dann auch sagen, dass man trackables in progress oder backlog braucht

2023-07-18 20:16 UTC, PhOberd commented on app/src/main/java/com/example/trackflix/fragments/random/RandomFragment.kt
> +                ((trackable.type == type)&&(trackable.progressState == "inProgress"))
k hab den backlog zustand in de funktion aufgnommen

2023-07-20 11:50 UTC, TheNerm approved these changes

2023-07-22 11:28 UTC, merged